create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  title text default 'Новый чат',
  summary text,
  metadata jsonb default '{}'::jsonb
);

alter table public.messages add column if not exists conversation_id bigint;
alter table public.messages add column if not exists metadata jsonb default '{}'::jsonb;

insert into public.conversations (title, summary, metadata)
select 'История', 'Импорт старых сообщений', '{"legacy_import": true}'::jsonb
where not exists (select 1 from public.conversations);

update public.messages
set conversation_id = (select id from public.conversations order by created_at asc limit 1)
where conversation_id is null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists conversations_set_updated_at on public.conversations;
create trigger conversations_set_updated_at
before update on public.conversations
for each row execute function public.set_updated_at();

create index if not exists conversations_updated_at_idx
  on public.conversations (updated_at desc);

create index if not exists messages_conversation_created_at_idx
  on public.messages (conversation_id, created_at);

alter table public.conversations enable row level security;
