-- Projects migration — выполните в Supabase → SQL Editor → Run
-- Создаёт таблицу projects и колонку project_id у чатов/файлов.

create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  title text not null default 'Новый проект',
  description text,
  metadata jsonb default '{}'::jsonb
);

alter table public.conversations
  add column if not exists project_id bigint references public.projects (id) on delete set null;

alter table public.documents
  add column if not exists project_id bigint references public.projects (id) on delete set null;

create index if not exists conversations_project_id_idx
  on public.conversations (project_id, updated_at desc);

create index if not exists documents_project_id_idx
  on public.documents (project_id, created_at desc);

create index if not exists projects_updated_at_idx
  on public.projects (updated_at desc);

create index if not exists projects_title_trgm_idx
  on public.projects using gin (title gin_trgm_ops);

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

alter table public.projects enable row level security;
