-- Supabase schema/migration for the Second Brain MVP.
-- Safe to run in an existing Supabase project with partially-created tables.
-- Project: https://slpnkzvetjhwchcobaig.supabase.co

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  role text,
  content text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.facts (
  id bigint generated by default as identity primary key,
  content text,
  source_message_id text,
  confidence numeric(4, 3),
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.entities (
  id bigint generated by default as identity primary key,
  name text,
  type text default 'unknown',
  description text,
  source_message_id text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text,
  status text default 'open',
  description text,
  due_at timestamptz,
  source_message_id text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.messages add column if not exists role text;
alter table public.messages add column if not exists content text;
alter table public.messages add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.messages add column if not exists created_at timestamptz default now();

alter table public.facts add column if not exists content text;
alter table public.facts add column if not exists fact text;
alter table public.facts add column if not exists source_message_id text;
alter table public.facts add column if not exists confidence numeric(4, 3);
alter table public.facts add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.facts add column if not exists created_at timestamptz default now();
alter table public.facts add column if not exists updated_at timestamptz default now();

alter table public.entities add column if not exists name text;
alter table public.entities add column if not exists type text default 'unknown';
alter table public.entities add column if not exists description text;
alter table public.entities add column if not exists source_message_id text;
alter table public.entities add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.entities add column if not exists created_at timestamptz default now();
alter table public.entities add column if not exists updated_at timestamptz default now();

alter table public.tasks add column if not exists title text;
alter table public.tasks add column if not exists status text default 'open';
alter table public.tasks add column if not exists description text;
alter table public.tasks add column if not exists due_at timestamptz;
alter table public.tasks add column if not exists source_message_id text;
alter table public.tasks add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.tasks add column if not exists created_at timestamptz default now();
alter table public.tasks add column if not exists updated_at timestamptz default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists facts_set_updated_at on public.facts;
create trigger facts_set_updated_at
before update on public.facts
for each row execute function public.set_updated_at();

drop trigger if exists entities_set_updated_at on public.entities;
create trigger entities_set_updated_at
before update on public.entities
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

create index if not exists messages_role_created_at_idx
  on public.messages (role, created_at desc);

create index if not exists facts_created_at_idx
  on public.facts (created_at desc);

create index if not exists facts_content_trgm_idx
  on public.facts using gin (content gin_trgm_ops);

create index if not exists facts_fact_trgm_idx
  on public.facts using gin (fact gin_trgm_ops);

create index if not exists entities_created_at_idx
  on public.entities (created_at desc);

create index if not exists entities_type_idx
  on public.entities (type);

create index if not exists entities_name_trgm_idx
  on public.entities using gin (name gin_trgm_ops);

create index if not exists tasks_created_at_idx
  on public.tasks (created_at desc);

create index if not exists tasks_status_idx
  on public.tasks (status);

create index if not exists tasks_title_trgm_idx
  on public.tasks using gin (title gin_trgm_ops);

alter table public.messages enable row level security;
alter table public.facts enable row level security;
alter table public.entities enable row level security;
alter table public.tasks enable row level security;

-- MVP note:
-- The Next.js API uses SUPABASE_SERVICE_ROLE_KEY on the server.
-- Service role bypasses RLS. Do not expose it to browser code.
-- For multi-user production, add user_id columns plus RLS policies.
